import {  Work_Sans } from "next/font/google";
import Header from "@/components/Header/Header";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.scss";
import Footer from "@/components/Footer/Footer";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Next Js Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={workSans.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
